### ISSUE TITLE
Chapter15 チャネルのページ内リンクが機能していない

### ISSUE THREAD

**Issue by yellowsman** [koga1020/phoenix-guide-ja-issues#1]
## 不備・不足の報告

Chapter15 チャネルに書かれている

> クライアントに必要なのは、適切なライブラリだけです。以下のクライアントライブラリの項を参照してください。

の「クライアントライブラリ」の部分に貼られているページ内リンクが和訳時にURLがズレたようで、機能していませんでした。

## URL

1. 対象のページ
https://zenn.dev/koga1020/books/phoenix-guide-ja-1-5/viewer/channels

2. 対象のリンクURL
https://zenn.dev/koga1020/books/phoenix-guide-ja-1-5/viewer/channels#client-libraries

3. 2.に設定されていて欲しいURL
https://zenn.dev/koga1020/books/phoenix-guide-ja-1-5/viewer/channels#クライアントライブラリ

**Comment by koga1020** [comment]
@yellowsman 確認遅くなりすみません 🙇 
ページ内リンクを修正しました、報告ありがとうございました！
