### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by toyoshi** [koga1020/phoenix-guide-ja-issues#2]
## 不備・不足の報告

>エイリアスは、ビュー、コントローラー、テンプレートで使用するためだけに自動的に設定されることに注意してください - これらの外では、フルネームか、モジュール定義の中で alias HelloWeb.Router.Helpers, as.Routes でモジュール定義の中で自分でエイリアスを設定する必要があります。

`alias HelloWeb.Router.Helpers, as.Routes` は `alias HelloWeb.Router.Helpers, as: Routes` が正しいと思われます

## URL

https://zenn.dev/koga1020/books/phoenix-guide-ja-1-6/viewer/routing

**Comment by koga1020** [comment]
@toyoshi 確認遅くなりすみません。修正反映いたしました、報告ありがとうございました！
