### ISSUE TITLE
チャネルのページのリンク不備

### ISSUE THREAD

**Issue by tamanugi** [koga1020/phoenix-guide-ja-issues#3]
ドキュメントの翻訳助かっています！
ありがとうございます！

## 不備・不足の報告

>それでは、簡単なチャットアプリケーションを作って、これらのアイデアをまとめてみましょう。新しいPhoenixアプリケーションを作成した](up_and_running)ことを確認してから、UserSocket を生成する準備をします

`新しいPhoenixアプリケーションを作成した](up_and_running)` の部分、リンクのマークダウンが切れてしまっているようです

## URL

https://zenn.dev/koga1020/books/phoenix-guide-ja-1-6/viewer/channels#%E3%81%99%E3%81%B9%E3%81%A6%E3%82%92%E7%B5%90%E3%81%B3%E4%BB%98%E3%81%91%E3%82%8B

**Comment by koga1020** [comment]
@tamanugi 報告ありがとうございます！修正いたしました 🚀 
<img width="807" alt="image" src="https://user-images.githubusercontent.com/11972942/171825106-397234cb-d955-47d6-bf11-2321306641a1.png">
